// backend/flask/vue/src/components/Nav.vue
<script setup>
import { RouterLink, RouterView, useRouter } from 'vue-router'
import {onBeforeMount, ref} from 'vue'

const router = useRouter()
const input_value = ref('')

function gotoResult(){
  router.push({name: 'search', params: {query : input_value.value} })
}
</script>

<template>
<nav>
    <h2>Menu</h2>
    <!-- TODO make loop -->
    <ul>
    <li><RouterLink :to="{name: 'home'}">Home</RouterLink></li>
    <li><RouterLink :to="{name: 'albums'}">Albums</RouterLink></li>
    <li><RouterLink :to="{name: 'artists'}">Artists</RouterLink></li>
    <li><RouterLink :to="{name: 'tracks'}">Tracks</RouterLink></li>
    </ul>
    <form @submit.prevent="gotoResult">
        <input type="search" name="q" placeholder="Search ..." v-model="input_value">
        <input type="submit" value="Go!">
    </form>
</nav> 
    
    
</template>

<style scoped>
nav {
    background-color: #6a1b9a;
    padding: 1.5em;
    width: 25%;
    text-align: center;
    min-height: 60vh;
}

ul {
    list-style-type: none;
    padding: 0;
    margin: 0;
}

li {
    padding: 0.5em;
}

form {
    padding: 0.5em;
}


</style>

// backend/flask/react-app/src/components/Nav.js
// import {NavLink} from 'react-router-dom'
import './Nav.css';
import {NavLink} from 'react-router-dom'

// TODO implement form
function Nav() {
    return ( 
    <nav>
    <h2>Menu</h2>
    <ul>
        <li><NavLink to="/">Home</NavLink></li>
        <li><NavLink to="albums">Albums</NavLink></li>
        <li><NavLink to="artists">Artists</NavLink></li>
        <li><NavLink to="tracks">Tracks</NavLink></li>
        <li><NavLink to="search">Search</NavLink></li>
    </ul>
            {/* <form>
            <input type="search" name="q" placeholder="Search ..." v-model="input_value">
            <input type="submit" value="Go!">
        </form> */}
    <form>
        <input type="search" name="q" placeholder="Search ..." />
        <input type="submit" value="Go!" />
    </form>
    </nav> 
     );
}

export default Nav;
